<%include file="acceptance_defaults.yml"/>
<%include file="default.yml"/>

build_command: |
               #!/bin/bash
               # Uncompress the qe dir
               tar -zxf qe.tar.gz
               cd qetest/pinot/spec
               ./jenkins_runner.sh region_settings:servers

job_description: "Owner: Platypus"
